### ISSUE TITLE
IUnityRenderingExtensions.h file not found

### ISSUE THREAD

**Issue by stopiccot** [iBicha/EmojiTexture#18] opened 2018-09-07 11:28 UTC
IUnityRenderingExtensions.h file not found error when building with Unity3D 2018.2.6f1 and Xcode 9.4.1

**Comment by iBicha** [comment] 2018-09-07 15:07
Hi @stopiccot 
Thank you for the bug report. But I couldn't reproduce the issue, after building with Unity3D 2018.2.6f1 and Xcode 9.4.1.
Can you provide any more info about this? Where does the error get thrown?

**Comment by stopiccot** [comment] 2018-09-09 13:27
Everything is pretty self-describing. Include file is missing.
Error is thrown when compiling `EmojiTexture.mm` file on line3:
`#include "IUnityRenderingExtensions.h"`
If everything compiles fine for you then this file should be located somewhere.
Could you please check where `IUnityRenderingExtensions.h` is located on your computer?
For example related `IUnityGraphics.h` file is located in `$(EXPORT_FOLDER)/Classes/Unity/IUnityGraphics.h`.

**Comment by stopiccot** [comment] 2018-09-09 13:41
Maybe your `/Applications/Unity/PlaybackEngines/iOSSupport/Trampoline/` folder is modified to contain this file?

**Comment by iBicha** [comment] 2018-09-09 15:17
I see. In your Unity project, the file should be located at `Assets/EmojiTexture/Plugins/iOS/IUnityRenderingExtensions.h`. When you select the file, make sure it is selected as an iOS plugin in the inspector

<img width="613" alt="screen shot 2018-09-09 at 9 16 27 am" src="https://user-images.githubusercontent.com/17722782/45265973-0e2bdf00-b411-11e8-9e64-18a331a6a99a.png">

**Comment by stopiccot** [comment] 2018-09-09 18:15
Maybe it should be added to git repo?

**Comment by stopiccot** [comment] 2018-09-09 19:29
Nice. The only thing I would like to note is that IUnityGraphics.h and IUnityInterface.h are already included in Xcode project in Classes/Unity folder so they are a bit excessive.

**Comment by iBicha** [comment] 2018-09-09 19:34
Yes they are, but they might change from one Unity version to another. This is to prevent an unexpected breaking change. Please feel free to close the issue if the problem is resolved

**Closed** 2018-09-09 19:41 UTC
